### ISSUE TITLE
All queries are open to SQL injection

### ISSUE THREAD

**Issue by cloudagon** [mitaai/usiran-data-store#11]
Use the tagged template literal for `queryRaw`, not the function as outlined [here](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#using-variables) or else your values will be unescaped.

[Reference file](https://github.com/mitaai/usiran-data-store/blob/master/graphql/Mutations/delete.ts)

**Comment by blms** [comment]
Hi @cloudagon, thanks for the report.

I've changed this to the tagged template literal but I'm now getting the following error:
```
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/87316f0/tokio-postgres/src/query.rs:142:5
expected 0 parameters but got 1
```
Any idea why that might be happening?

**Comment by cloudagon** [comment]
When is the error happening?

**Comment by blms** [comment]
On any call to `$queryRaw` that involves a `DELETE` SQL command (in other words, those ones that I modified per this issue).

Note that I've been successfully using the tagged template literal [in these queries](https://github.com/mitaai/usiran-data-store/blob/ce672a0efed0e573c4e129c2486ee35e77dfeb07/graphql/Queries/search.ts#L16-L55) previously with no problems, but they are just `SELECT` queries.

**Comment by cloudagon** [comment]
Perhaps because you have quotes around the string IDs still?
So change this:
```js
await ctx.db.$queryRaw`DELETE FROM "BriefingBookDocument" WHERE "B" = '${args.where.id}';`
```
to this:
```js
await ctx.db.$queryRaw`DELETE FROM "BriefingBookDocument" WHERE "B" = ${args.where.id};`
```

**Comment by blms** [comment]
Thanks @cloudagon, that was it!

**Comment by cloudagon** [comment]
Awesome!
